# Generated by Django 3.1 on 2021-07-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('header', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('contaners', models.TextField()),
                ('title_prices', models.IntegerField()),
                ('ul_1', models.CharField(blank=True, max_length=200)),
                ('ul_2', models.CharField(blank=True, max_length=200)),
                ('ul_3', models.CharField(blank=True, max_length=200)),
                ('ul_4', models.CharField(blank=True, max_length=200)),
                ('ul_5', models.CharField(blank=True, max_length=200)),
                ('ul_6', models.CharField(blank=True, max_length=200)),
                ('ul_7', models.CharField(blank=True, max_length=200)),
                ('ul_8', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('experienced_staff_1', models.CharField(blank=True, max_length=200)),
                ('experienced_staff_description_1', models.TextField(blank=True)),
                ('experienced_s_images', models.ImageField(blank=True, upload_to='')),
                ('experienced_staff_2', models.CharField(blank=True, max_length=200)),
                ('experienced_staff_description_2', models.TextField(blank=True)),
                ('experienced_stimage', models.ImageField(blank=True, upload_to='')),
                ('experienced_staff_3', models.CharField(blank=True, max_length=200)),
                ('experienced_staff_description_3', models.TextField(blank=True)),
                ('experiencedsta_image', models.ImageField(blank=True, upload_to='')),
                ('experienced_staff_4', models.CharField(blank=True, max_length=200)),
                ('experienced_staff_description_4', models.TextField(blank=True, max_length=200)),
                ('experienced_stafimage', models.ImageField(blank=True, upload_to='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
