# Generated by Django 3.1 on 2021-07-30 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Our_services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='experienced_stafimage',
            new_name='experienced_stafimagess',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='experienced_stimage',
            new_name='experienced_stimagess',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='experiencedsta_image',
            new_name='experiencedsta_imagessss',
        ),
    ]
