# Generated by Django 3.1 on 2021-07-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Our_services', '0002_auto_20210730_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='experienced_stimagess',
            new_name='experiencedimg',
        ),
    ]
