# Generated by Django 3.1 on 2021-07-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Our_services', '0003_auto_20210730_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='experiencedimg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
