# Generated by Django 3.1 on 2021-07-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chdomestic',
            fields=[
                ('srl', models.AutoField(primary_key=True, serialize=False)),
                ('domestic', models.BooleanField()),
                ('commercial', models.BooleanField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
