# Generated by Django 3.1 on 2021-08-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookzipcode', '0002_auto_20210805_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='email',
            field=models.EmailField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='infection',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='service_details',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='total_price',
            field=models.IntegerField(blank=True),
        ),
    ]
