# Generated by Django 3.1 on 2021-08-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookzipcode', '0003_auto_20210805_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
