# Generated by Django 3.1 on 2021-08-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookzipcode', '0004_auto_20210805_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookorder',
            name='Ph',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='appointment_timing_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='flat_bulding_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='street_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
