# Generated by Django 3.1 on 2021-08-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookzipcode', '0007_auto_20210809_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookorder',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='note_final',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
