# Generated by Django 3.1 on 2021-08-10 06:42

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookzipcode', '0009_auto_20210810_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='user_description',
            field=django_quill.fields.QuillField(),
        ),
    ]
