# Generated by Django 3.1 on 2021-08-10 06:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('bookzipcode', '0010_auto_20210810_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='user_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
