# Generated by Django 3.1 on 2021-08-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookzipcode', '0017_auto_20210812_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='infection_control_cleaning_services_No',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='infection_control_cleaning_services_yes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
