# Generated by Django 3.1 on 2021-08-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookzipcode', '0018_auto_20210812_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookorder',
            old_name='please_tell_us_about_your_place',
            new_name='please_tell_us_about_your_place1',
        ),
        migrations.AddField(
            model_name='bookorder',
            name='please_tell_us_about_your_place2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='please_tell_us_about_your_place3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='please_tell_us_about_your_place4',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
