# Generated by Django 3.1 on 2021-08-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookzipcode', '0019_auto_20210813_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookorder',
            name='most_of_our_customers_who_book_after_builders_cleaning_also_include2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='most_of_our_customers_who_book_after_builders_cleaning_also_include',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
