# Generated by Django 3.1 on 2021-07-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='check',
        ),
    ]
