# Generated by Django 3.1 on 2021-07-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about',
        ),
    ]
