# Generated by Django 3.1 on 2021-07-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='covid_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='maintenance_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
