# Generated by Django 3.1 on 2021-07-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_post_wellcome_msg2'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homelist', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='what_make_li_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='what_make_li_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='what_make_li_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='what_make_li_4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='what_make_li_5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='what_make_li_6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='what_make_li_7',
        ),
    ]
