# Generated by Django 3.1 on 2021-07-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210729_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
