# Generated by Django 3.1 on 2021-07-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='footer_header',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='footer_image_1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='footer_image_1_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='footer_image_1_header',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='footer_image_2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='footer_image_2_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='footer_image_2_header',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='foter_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='heade2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='header',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='side_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
