# Generated by Django 3.1 on 2021-07-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20210729_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='heade2',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
